import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartPreviewProvider } from "@/context/CartPreviewContext";
import { CustomerProvider } from "@/context/CustomerContext";
import { GlobalUIProvider } from "@/context/GlobalUIContext";
import { Toaster } from "react-hot-toast";
import { CategoryProvider } from "@/context/CategoryContext";
import FloatingCartPreview from "@/ui/FloatingCartPreview";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster />
        <GlobalUIProvider>
          <CustomerProvider>
            <CategoryProvider>
              <CartPreviewProvider>
                {children}
                <FloatingCartPreview />
              </CartPreviewProvider>
            </CategoryProvider>
          </CustomerProvider>
        </GlobalUIProvider>
      </body>
    </html>
  );
}
